### ISSUE TITLE
Why not just mounting the traefik.toml

### ISSUE THREAD

**Issue by Toflar** [containerize-my-server/reverse-proxy#1]
Hey Nils,

Thanks for sharing your insights. I was just wondering why you build the image and don't just mount the `traefik.toml` file? Imho there's no real need for that.

**Comment by nknapp** [comment]
Probably because... well, yes, actually you are right. The thought just didn't occur to me.
That would prevent the need to rebuild and restart the container when the configuration changes. The important thing for me was that the whole setup could be put into a git-repository.

Feel free to make a PR. Or I may change it myself when I find some time.

**Comment by Toflar** [comment]
Hehe, I found it very helpful so thank you again for publishing it! I was just wondering if there was any special reason for it I did not see :-) I'll provide a PR when I finished my tests ;-)

**Comment by Toflar** [comment]
So I ended up putting it into an image too because I wanted to distribute it on multiple hosts using swarm mode. I think people working with Docker on a regular basis will know the difference or find this issue then :) Thanks again!
