### ISSUE TITLE
Similar Repo

### ISSUE THREAD

**Issue by MathiasRenner** [containerize-my-server/reverse-proxy#11]
Hey @nknapp I just saw your repo after I created one about traefik and docker yesterday: 
https://github.com/bitleaf/simple-traefik-proxy-and-services

You don't seem to have documented any apps that users can checkout and startup within the twinkling of an eye. I'd be glad if you contribute some if you use any! Thanks in advance!

**Comment by nknapp** [comment]
Most of my containers are more complex and customized for my own purposes. At the moment, I am reluctant to share them, because of the effort it involves (i.e. making them universally usable).

I don't like duplicates though. You say, you created your repo yesterday. Would you like to join the the `containerize-my-server`-org and merge the repos? As long as @vegasbrianc has no objections.

**Comment by MathiasRenner** [comment]
Thank you very much for asking me to join your org. I really like the name of it :-)

However, I feel like I'll stay with my repo and extend it there. Meanwhile I have several services there and a very easy to follow documentation. This repo lacks both, I am only jealous about the mulitple stars it already got :)
